### PR TITLE
No more dangling commas.

### PR DESCRIPTION
**Pull request by qubyte**
After a conversation, we're thinking of reversing the dangling comma rule. This PR also removes some redundant stuff:

 - `env` should be configured per repository anyway.
 - The removed globals should only be active in test directories, and that should be done by adding a eslintrc.json file like this to said directories:

```json
{
  "env": {
    "mocha": true
  }
}
```

### CODE REVIEW

**Review by inca — APPROVED** [review]
Nice 👍

**Comment by qubyte** [comment]
IMPORTANT: This is an extension of a discussion in #dev. I won't go any further until everyone has had their chance to be heard. Consider it a proposal.

**Comment by muzafarova** [comment]
hm... this rule it the most useful imho) I'd like to keep using it in Backoffice

What if we make it `only-multiline` – allows (but does not require) trailing commas when the last element or property is in a different line than the closing ] or } and disallows trailing commas when the last element or property is on the same line as the closing ] or }
?

**Comment by qubyte** [comment]
Strictness seems preferable (one style or the other, but never both). This rule can be overridden locally in backoffice though, to preserve the existing behaviour there. :)

**Comment by inca** [comment]
When we were discussing this we gathered more cons than pros in keeping this rule (in short, it seems to directly affect productivity, even though having the habit doesn't make it immediately obvious).

We realize that same ruleset can't fit everyone's habits. So if there's a strong opinion against changing that, let's hear it.

**Review by randunel — APPROVED** [review]

**Comment by randunel** [comment]
> Strictness seems preferable (one style or the other, but never both).

You seem to be limiting the scope of „strictness” per project, instead of per team or organisation. Why not per file? Or per directory? Or per infrastructure (imagine a ruleset for roxi, one for backbone - _one style or another, never both_ in the same infrastructure)?

**Comment by qubyte** [comment]
I should clarify... By strictness I mean a consistent code style within each repository (and not necessarily beyond) should be enforced. I think most, if not all, of our repositories do more than simply extend the config in this repo (which makes sense since repositories have unique concerns). The ubio config in this repository is a set of defaults/recommendations.

**Comment by randunel** [comment]
Ok, but why a consistent code style within each repository, and not within each infrastructure or each team?

**Comment by qubyte** [comment]
I prefer consistency over the whole company. I don't think it should be forced though. The mimimum is within a repository.

**Review by 1602 — APPROVED** [review]

**Pull request merged**
